# Generated by Django 3.0.7 on 2020-07-04 13:19

from django.db import migrations, models
import playapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('m_file', models.FileField(null=True, upload_to='sound', validators=[playapp.validators.validate_is_audio], verbose_name='音楽ファイル')),
            ],
        ),
    ]
